//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Виды_питомцев> Виды_питомцев { get; set; }
        public virtual DbSet<Номера_гостиницы> Номера_гостиницы { get; set; }
        public virtual DbSet<Оплата_услуг> Оплата_услуг { get; set; }
        public virtual DbSet<Питомцы> Питомцы { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Проживание> Проживание { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Услуга_от_сотрудника> Услуга_от_сотрудника { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<Хозяева> Хозяева { get; set; }
        public virtual DbSet<Журнал_услуг> Журнал_услуг { get; set; }
    }
}
