//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журнал_услуг
    {
        public System.Guid ID_проживания { get; set; }
        public string Код_услуги { get; set; }
        public System.Guid ID_сотрудника { get; set; }
        public System.DateTime Дата_и_время { get; set; }
    
        public virtual Проживание Проживание { get; set; }
        public virtual Услуга_от_сотрудника Услуга_от_сотрудника { get; set; }
    }
}
