//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата_услуг
    {
        public System.Guid ID_оплаты { get; set; }
        public System.Guid ID_проживания { get; set; }
        public System.DateTime Дата_и_время { get; set; }
        public decimal Сумма { get; set; }
    
        public virtual Проживание Проживание { get; set; }
    }
}
