//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Питомцы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Питомцы()
        {
            this.Проживание = new HashSet<Проживание>();
        }
    
        public System.Guid ID_питомца { get; set; }
        public System.Guid ID_хозяина { get; set; }
        public string Кличка { get; set; }
        public string Код_вида_питомца { get; set; }
        public string Порода { get; set; }
        public bool Пол { get; set; }
        public int Год_рождения { get; set; }
    
        public virtual Виды_питомцев Виды_питомцев { get; set; }
        public virtual Хозяева Хозяева { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проживание> Проживание { get; set; }
    }
}
