//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проживание
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проживание()
        {
            this.Оплата_услуг = new HashSet<Оплата_услуг>();
            this.Журнал_услуг = new HashSet<Журнал_услуг>();
        }
    
        public System.Guid ID_проживания { get; set; }
        public System.Guid ID_питомца { get; set; }
        public int Номер_гостиницы { get; set; }
        public System.DateTime Дата_прибытия { get; set; }
        public System.DateTime Дата_выбытия { get; set; }
        public bool Нужда_в_медикаментах { get; set; }
    
        public virtual Номера_гостиницы Номера_гостиницы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оплата_услуг> Оплата_услуг { get; set; }
        public virtual Питомцы Питомцы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал_услуг> Журнал_услуг { get; set; }
    }
}
