//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуга_от_сотрудника
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуга_от_сотрудника()
        {
            this.Журнал_услуг = new HashSet<Журнал_услуг>();
        }
    
        public string Код_услуги { get; set; }
        public System.Guid ID_сотрудника { get; set; }
        public double Доля_от_всех_обязанностей { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал_услуг> Журнал_услуг { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
